[package]
name = "digests-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
bumpalo = "3"
libc = "0.2"
chrono = { version = "0.4", features = ["clock"] }
digests-feed = { path = "../feed" }
